<a href="https://colab.research.google.com/github/yeon110/test/blob/main/mg%EC%97%90%EC%84%9C_ppm%EB%B3%80%ED%99%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file='/content/drive/MyDrive/공공데이터인턴/국내1_end.xlsx'

In [ ]:
import pandas as pd
df=pd.read_excel(file)
df.head()

,CAS번호,상태,UEL,LEL,인화점,발화점,증기압,끓는점,분자량,IDLH,PAC-2
0,75-31-0,·액체,·10.4%,·2.0%·2.3%,·-37.22℃,·402℃,·579.6mmHg@25℃·477.78mmHg@20℃,·33-34℃·32-34℃,·59.11·59.08,·750ppm,·150ppm
1,681-84-5,·액체,·자료없음,·자료없음,·96.11℃,·240℃,·10.13mmHg@25℃·18mmHg@25℃,·121-122℃@760mmHg·121℃,·152.25,·해당사항없음,·0.91Appm
2,57-92-1,·분말(고체),·자료없음,·자료없음,·자료없음,·자료없음,·적용안됨,·적용안됨,·581.58·581.67,·해당사항없음,·해당사항없음
3,75-12-7,·오일류액체,·19.0%,·2.7%,·154.44℃·175℃,·500℃·>500℃,·6.10X10-2mmHg@25℃·29.25mmHg@130℃,·210.5℃@760mmHg·210℃,·45.04·45.05,·해당사항없음,·125ppm
4,75-20-7,·불규칙한덩어리(고체)또는사방정계결정(고체)·불규칙하며단단한고체,·자료없음,·자료없음,·자료없음,·자료없음,·자료없음,"·2,300℃",·64.10,·해당사항없음,·50mg/m3

In [ ]:
cas=df['CAS번호'].tolist()
molecular=df['분자량'].tolist()
idlh=df['IDLH'].tolist()
pac=df['PAC-2'].tolist()

In [ ]:
len(df)

6763

In [ ]:
mole=pd.DataFrame({'cas':cas,'molecular weight':molecular,'IDLH':idlh,'pac-2':pac})

In [ ]:
molecular_c=molecular.copy()
idlh_c=idlh.copy()
pac_c=pac.copy()

In [ ]:
mole.head()

        cas molecular weight     IDLH      pac-2
0   75-31-0     ·59.11·59.08  ·750ppm    ·150ppm
1  681-84-5          ·152.25  ·해당사항없음  ·0.91Appm
2   57-92-1   ·581.58·581.67  ·해당사항없음    ·해당사항없음
3   75-12-7     ·45.04·45.05  ·해당사항없음    ·125ppm
4   75-20-7           ·64.10  ·해당사항없음   ·50mg/m3

In [ ]:
#idlh, pac-2-국내
sum=0
idlh_f=[]
pac_f=[]

for i in range(len(idlh_c)):
  if idlh_c[i] == '-' or pac_c[i] == '-':
    idlh_f.append(idlh_c[i])
    pac_f.append(pac_c[i])
  elif mole.iloc[i,2] == 'HSDB':
    idlh_f.append('HSDB')
    pac_f.append(mole.iloc[i,3].split('·')[1])
  else:
    idlh_f.append(mole.iloc[i,2].split('·')[1])
    pac_f.append(mole.iloc[i,3].split('·')[1])

In [ ]:
print(len(idlh_f))
print(len(pac_f))

6763
6763

In [ ]:
#분자량-국내
import re
mole_f=[]
for i in range(len(molecular_c)):
  m=molecular_c[i]
  if m == '-':
    mole_f.append(m)
  else:
    mole_f1=m.split('·')[1]
    
    if '-' or '~' in m:
      mole_f2=re.split('[-~]',mole_f1)
      mole_f.append(mole_f2[0])
    else:
      mole_f.append(mole_f1)
  

print(len(mole_f))

6763

In [ ]:
mole_df=pd.DataFrame({'CAS번호':cas,'molecular weight':mole_f,'IDLH':idlh_f,'PAC-2':pac_f})

In [ ]:
mole_df

            CAS번호 molecular weight    IDLH     PAC-2
0         75-31-0            59.11  750ppm    150ppm
1        681-84-5           152.25  해당사항없음  0.91Appm
2         57-92-1           581.58  해당사항없음    해당사항없음
3         75-12-7            45.04  해당사항없음    125ppm
4         75-20-7            64.10  해당사항없음   50mg/m3
...           ...              ...     ...       ...
6758  156509-98-7             자료없음  해당사항없음    해당사항없음
6759  191175-18-5             자료없음  해당사항없음    해당사항없음
6760  100346-90-5             자료없음  해당사항없음    해당사항없음
6761   25965-81-5             자료없음  해당사항없음    해당사항없음
6762  177345-75-4             자료없음  해당사항없음    해당사항없음

[6763 rows x 4 columns]

In [ ]:
mole_df.iloc[0,3]

'150ppm'

In [ ]:
pac_cal=[]
idlh_cal=[]
for i in range(len(mole_df)):

  if 'ppm' in mole_df.iloc[i,3]:
    p=mole_df.iloc[i,3]
    p=p.strip()
    if '*' in p:
      p=p.split('*')[0]
    else:
      p=p.split('ppm')[0]
    pac_cal.append(str(p)+' ppm')

  elif 'mg' in mole_df.iloc[i,3]:
    a=mole_df.iloc[i,3]
    a=a.strip()
    mg=a.split('mg')[0]
    
    w=mole_df.iloc[i,1]
    wei=w.strip()
    
    try:
      if float(wei) == 0:
        pac_cal.append('-')
      else:
        ppm=int(float(mg)*24.45/float(wei))
        z=str(ppm)+' ppm'
        z=z.strip()
        pac_cal.append(z)
      
    except ValueError:
      c=mole_df.iloc[i,3]
      c=c.strip()
      c=str(c.split('mg')[0])+'mg/m3'
      pac_cal.append(c)
  
  else:
    pac_cal.append('-')
  
  if 'ppm' in mole_df.iloc[i,2]:
    m=mole_df.iloc[i,2]
    m=m.strip()
    if '*' in m:
      m=m.split('*')[0]
    else:
      m=m.split('ppm')[0]
    idlh_cal.append(str(m)+' ppm')

  elif 'mg' in mole_df.iloc[i,2]:
    b=mole_df.iloc[i,2]
    b=b.strip()
    mg=b.split('mg')[0]
    
    try:
      if float(wei) == 0:
        idlh_cal.append('-')
      else:
        ppm=int(float(mg)*24.45/float(wei))
        z=str(ppm)+' ppm'
        z=z.strip()
        idlh_cal.append(z)
      
    except ValueError:
      c=mole_df.iloc[i,2]
      c=str(c.split('mg')[0])+'mg/m3'
      c=c.strip()
      idlh_cal.append(c)
  else:
    idlh_cal.append('-')

0
9
11
15
23
47
74
77
135
287
300
357
376
390
392
471
645
678
703
840
985
1126
1409
1411
1498
1499
1514
1517
1583
1595
1636
1638
1779
1780
1782
1783
1785
1786
1806
1815
1903
2845
2922
2954
3148
3150
3174
3183
3288
3291
3306
3309
3322
4005
4007
4008
4009
4010
4013
4014
4027
4028
4043
4045
4047
4050
4051
4055
4062
4064
4065
4067
4068
4069
4070
4072
4076
4077
4110
4118
4119
4120
4121
4129
4132
4138
4139
4141
4142
4143
4146
4148
4149
4151
4154
4160
4163
4165
4167
4168
4169
4171
4174
4175
4183
4184
4185
4186
4187
4189
4190
4191
4196
4198
4201
4203
4204
4205
4206
4207
4210
4211
4215
4216
4217
4218
4220
4221
4228
4231
4233
4280
4283
4295
4301
4304
4305
4306
4310
4311
4315
4318
4319
4354
4366
4377
4408
4411
4414
4415
4418
4441
4492
4494
4568
4591
4616
4619
4640
4658
4674
4701
4705
4707
4718
4725
4735
4749
4753
4759
4761
4766
4767
4769
4781
4783
4785
4786
4791
4794
4805
4806
4807
4822
4823
4824
4829
4839
4854
4858
4860
4861
4889
4893
4895
4897
4898
4899
4901
4902
4903
4904
4906
4907
4910
4912
4914
4918
4922
4923
4927
4929
4942
4950
4954
4955
4960
4967
4982
4988
4992
4997
5000
5004
5005
5010
5016
5023
5024
5030
5033
5034
5035
5036
5041
5044
5046
5050
5061
5066
5068
5104
5119
5136
5137
5139
5140
5149
5166
5169
5170
5174
5179
5447
5574
5576
5579

In [ ]:
print(len(pac_cal))
print(len(idlh_cal))

6763
6763

In [ ]:
idlh_cal.count('-')

6242

In [ ]:
ppm_df=pd.DataFrame({'CAS번호':cas.'molecular weight':mole_f,'IDLH':idlf_cal,'PAC-2':pac_cal})

SyntaxError: ignored

In [ ]:
ppm_f=[]
for i in range(len(mole_df)):

  if 'ppm' in mole_df.iloc[i,2]:
    b=mole_df.iloc[i,2]
    b=str(b.split('ppm')[0])+'ppm'
    b=b.strip()
    ppm_f.append(b)

  elif 'mg' in mole_df.iloc[i,2]:
    a=mole_df.iloc[i,2]
    mg=a.split(' ')[1]
    
    w=mole_df.iloc[i,1]
    wei=w.split(' ')[1]
    
    try:
      ppm=int(float(mg)*24.45/float(wei))
      z=str(ppm)+' ppm'
      z=z.strip()
      ppm_f.append(z)
      
    except ValueError:
      c=mole_df.iloc[i,2]
      c=str(c.split('mg')[0])+'mg/m3'
      c=c.strip()
      ppm_f.append(c)
  
  elif  'A potential occupational carcinogen.(NIOSH, 2022)' in mole_df.iloc[i,2]:
    ppm_f.append('-')

  else:
    ppm_f.append('-')

In [ ]:
#이전 자료
ppm_f=[]
for i in range(len(mole_df)):

  if 'ppm' in mole_df.iloc[i,2]:
    b=mole_df.iloc[i,2]
    b=str(b.split('ppm')[0])+'ppm'
    b=b.strip()
    ppm_f.append(b)

  elif 'mg' in mole_df.iloc[i,2]:
    a=mole_df.iloc[i,2]
    mg=a.split(' ')[1]
    
    w=mole_df.iloc[i,1]
    wei=w.split(' ')[1]
    
    try:
      ppm=int(float(mg)*24.45/float(wei))
      z=str(ppm)+' ppm'
      z=z.strip()
      ppm_f.append(z)
      
    except ValueError:
      c=mole_df.iloc[i,2]
      c=str(c.split('mg')[0])+'mg/m3'
      c=c.strip()
      ppm_f.append(c)
  
  elif  'A potential occupational carcinogen.(NIOSH, 2022)' in mole_df.iloc[i,2]:
    ppm_f.append('-')

  else:
    ppm_f.append('-')

IndexError: ignored

In [ ]:
len(ppm_f)

6763

In [ ]:
df_f=pd.DataFrame({'CAS번호':cas,'끝점농도':ppm_f})

In [ ]:
df_f.to_excel('drive/My Drive/공공데이터인턴/ppm_국내1-6763.xlsx', index=False)

In [ ]:
int(4.1325)

4

In [ ]:
file_1='/content/drive/MyDrive/공공데이터인턴/ppm_1-10000.xlsx'
import pandas as pd
df_1=pd.read_excel(file_1)
df_1.head()

         CAS번호 끝점농도
0  999999-99-4    -
1   99963-78-7    -
2   99948-84-2    -
3   99948-83-1    -
4   99924-40-0    -

In [ ]:
file_2='/content/drive/MyDrive/공공데이터인턴/ppm_10000-20000.xlsx'
import pandas as pd
df_2=pd.read_excel(file_2)
df_2.head()

        CAS번호 끝점농도
0  68958-22-5    -
1  68958-21-4    -
2  68958-19-0    -
3  68958-12-3    -
4  68958-10-1    -

In [ ]:
file_3='/content/drive/MyDrive/공공데이터인턴/ppm_20000-30000.xlsx'
import pandas as pd
df_3=pd.read_excel(file_3)
df_3.head()

        CAS번호 끝점농도
0   5964-35-2    -
1  59633-97-5    -
2   5962-42-5    -
3   5961-55-7    -
4    596-75-8    -

In [ ]:
file_4='/content/drive/MyDrive/공공데이터인턴/ppm_30000-40000.xlsx'
import pandas as pd
df_4=pd.read_excel(file_4)
df_4.head()

         CAS번호 끝점농도
0  190394-85-5    -
1   19034-12-9    -
2  190280-68-3    -
3  190280-67-2    -
4  190280-66-1    -

In [ ]:
file_5='/content/drive/MyDrive/공공데이터인턴/ppm_40000-42550.xlsx'
import pandas as pd
df_5=pd.read_excel(file_5)
df_5.head()

         CAS번호 끝점농도
0  101316-71-6    -
1  101316-70-5    -
2  101316-69-2    -
3  101316-68-1    -
4  101316-67-0    -

In [ ]:
df_ppm_f=pd.concat([df_1,df_2,df_3,df_4,df_5])

In [ ]:
len(df_ppm_f)

42520

In [ ]:
df_ppm_f.to_excel('drive/MyDrive/공공데이터인턴/ppm변환.xlsx',index=False)